### ISSUE TITLE
compat issues reloaded

### ISSUE THREAD

**Issue by lindnemi** [JuliaEnergy/PowerDynamics.jl#99] opened 2020-07-06 10:05 UTC
Apparently the issue https://github.com/JuliaEnergy/PowerDynamics.jl/issues/89  is back since we upgraded to 0.3.1

if I install ND 0.3.1 first, and then PD I get version 2.2
if I install PD 2.3 first, and then ND I get version 0.1

**Comment by SabineAuer** [comment] 2020-07-06 17:13
Well, the problem is that we did not initiate a new release, yet. The problem is fixed in the master but if you install PD via the package manager it takes the last release. You could also install it from the master directly.
We can also do a new minor release in the next time to make the installation process easier for you.

**Comment by lindnemi** [comment] 2020-07-07 08:03
Why not immediately release PD 2.3.1? I think it would be quite important, since anybody not aware of the master / repository difference will install it via the package manager and ND 0.1 is outdated since 6 month and considerably slower.

This problem keeps coming up, Rapha approached me because of an error he kept seeing and he told me that Mehrnaz has run into similar issues.

**Comment by SabineAuer** [comment] 2020-07-10 10:20
I will make a minor release this weekend ;).

**Comment by SabineAuer** [comment] 2020-07-10 11:37
The new release is available now: https://github.com/JuliaEnergy/PowerDynamics.jl/releases/tag/v2.3.1
Can I close this issue then?

**Comment by lindnemi** [comment] 2020-07-11 11:16
Great. It seems to be working now :)

**Comment by lindnemi** [comment] 2020-08-14 08:13
Issue is happening again since version 0.4. I realized now that semantic versioning for versions that start with a 0 is different and hence to avoid this behaviour the next ND versions will be 0.4.1, 0.4.2 and so on. I guess one last time we will have to change the compat section of PowerDynamics though

https://julialang.github.io/Pkg.jl/v1/compatibility/#compat-pre-1.0-1

**Comment by lindnemi** [comment] 2020-08-14 08:16
ok, i see... once again this is fixed in master (maybe automatically by the compat helper?) but not in the current release... so there is nothing else to do then to wait for the next minor release.

**Comment by lindnemi** [comment] 2020-08-14 08:18
https://github.com/JuliaEnergy/PowerDynamics.jl/commit/fa3ce6fbb640e25a6aef2a5cde8cdb0945be36fa#diff-910a7b3ca0075d545dcec45cb7335ca9 

Paul was the compat helper :D

**Comment by SabineAuer** [comment] 2020-08-14 09:11
@lindnemi : I will create a new minor release. I know, the process takes some time but I think it is the best way to ensure PowerDynamics is compatible with all packages, to first run PRs, test them, merge them into the master and then make minor releases once in a while.

**Comment by SabineAuer** [comment] 2020-08-14 22:01
With the new release [2.3.2](https://github.com/JuliaEnergy/PowerDynamics.jl/releases/tag/v2.3.2) I will close this issue again

**Closed by SabineAuer** 2020-08-14 22:01 UTC
