### ISSUE TITLE
Compatibility with NetworkDynamics 0.3.0

### ISSUE THREAD

**Issue by lindnemi** [JuliaEnergy/PowerDynamics.jl#89] opened 2020-04-09 08:55 UTC
We released a new version of NetworkDynamics. Computations can be executed on parallel architectures if `network_dynamics` is called with the keyword `parallel=true`. It should be fully compatible with the current version of PowerDynamics. However I noticed an issue with Pkg and the current versioning:

* upgrading to NetworkDynamics 0.3.0 leads to a downgrade of PowerDynamics 2.3.0 -> 2.2.0. 

* when installing PowerDynamics 2.3.0 in a new environment and then adding NetworkDynamics, iit gets added in version 0.1.0

**Comment by luap-pik** [comment] 2020-05-15 13:03
This is weird. In the `Project.toml` it reads 
```
NetworkDynamics = "^0.2.0"
```
so how can it install version 0.1.0?

**Comment by luap-pik** [comment] 2020-05-15 13:09
This seems to be addressed by #84

**Comment by SabineAuer** [comment] 2020-05-18 12:24
NetworkDynamics = "^0.2.0" only allows the following version range [0.2.0,0.3.0) and excludes version 0.3.0 I am not sure about the downgrading to 0.1.0 and whether this was triggered by totally downgrading PowerDynamics to an older version. Please check whether this PR fixes that: https://github.com/JuliaEnergy/PowerDynamics.jl/pull/94

**Comment by luap-pik** [comment] 2020-05-18 14:23
I tested #94 in a new environment, NetworDynamics is correctly added as 0.3.0. 
The sequence of `add`s does not matter.

@lindnemi  I could not reproduce the downgrading to 0.1.0. For me it was 0.2.0

**Closed** 2020-05-22 07:42 UTC
